defmodule VideoConferenceWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :video_conference

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_video_conference_key",
    signing_salt: "Fd9u/dhM",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # check_origin: ["//*.example.com"]
  # TODO correct check_origin: ["//*.example.com"]
  # websocket: true,
  socket "/socket", VideoConferenceWeb.GroupSocket,
    websocket: [check_origin: false],
    longpoll: false,
    auth_token: true

  socket "/socket/phone", VideoConferenceWeb.PhoneSocket,
    websocket: [check_origin: false],
    longpoll: false,
    auth_token: true

  plug CORSPlug, origin: "*"

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :video_conference,
    gzip: not code_reloading?,
    only: VideoConferenceWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :video_conference
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug VideoConferenceWeb.Router
end
